name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 6
          - 8
          - 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # TODO: commit package-lock.json and replace with clean-install
      - run: npm install
      - run: npm run bootstrap
      - run: npm run test
